"""대형 헤지펀드·자산운용사 13F 제출 기관 레지스트리 (CIK 기준)."""

from __future__ import annotations

# id, 한글명, 대표/설명, CIK (zero-padded 없이)
INSTITUTIONS_13F: list[dict[str, str]] = [
    {"id": "berkshire", "name": "버크셔 해서웨이", "manager": "워렌 버핏", "cik": "1067983"},
    {"id": "bridgewater", "name": "브릿지워터", "manager": "레이 달리오", "cik": "1350694"},
    {"id": "citadel", "name": "시타델", "manager": "켄 그리핀", "cik": "1423053"},
    {"id": "renaissance", "name": "르네상스", "manager": "짐 사이먼스", "cik": "1037389"},
    {"id": "pershing", "name": "퍼싱 스퀘어", "manager": "빌 애크먼", "cik": "1336528"},
    {"id": "tiger", "name": "타이거 글로벌", "manager": "체이스 콜먼", "cik": "1167483"},
    {"id": "baupost", "name": "바포스트", "manager": "세스 클라만", "cik": "1061768"},
    {"id": "appaloosa", "name": "아팔루사", "manager": "데이비드 테퍼", "cik": "1656456"},
    {"id": "duquesne", "name": "듀케인 패밀리", "manager": "스탠 드러크밀러", "cik": "1536411"},
    {"id": "scion", "name": "사이언 에셋", "manager": "마이클 버리", "cik": "1649339"},
    {"id": "blackrock", "name": "블랙록", "manager": "래리 핑크", "cik": "1364742"},
    {"id": "vanguard", "name": "뱅가드", "manager": "", "cik": "0102909"},
    {"id": "state_street", "name": "스테이트 스트리트", "manager": "", "cik": "0093751"},
    {"id": "fidelity", "name": "피델리티", "manager": "", "cik": "0315066"},
    {"id": "millennium", "name": "밀레니엄", "manager": "이스라엘 엥겔", "cik": "1273087"},
    {"id": "point72", "name": "포인트72", "manager": "스티븐 코헨", "cik": "1603466"},
    {"id": "two_sigma", "name": "투 시그마", "manager": "", "cik": "1179392"},
    {"id": "deshaw", "name": "D.E. Shaw", "manager": "데이비드 쇼", "cik": "1009207"},
    {"id": "elliott", "name": "엘리엇", "manager": "폴 싱어", "cik": "1793497"},
    {"id": "third_point", "name": "서드 포인트", "manager": "댄 로브", "cik": "1040273"},
    {"id": "viking", "name": "바이킹 글로벌", "manager": "안드레아스 할보르센", "cik": "1103809"},
    {"id": "lone_pine", "name": "론 파인", "manager": "스티븐 만델", "cik": "1061165"},
    {"id": "coatue", "name": "코투", "manager": "필리프 라폰", "cik": "1535392"},
    {"id": "d1", "name": "D1 캐피털", "manager": "댄 갤런트", "cik": "1747057"},
    {"id": "soros", "name": "소로스 펀드", "manager": "조지 소로스", "cik": "1029160"},
    {"id": "trian", "name": "트리안", "manager": "넬슨 펠츠", "cik": "1345471"},
    {"id": "valueact", "name": "밸류액트", "manager": "제프리 우븐", "cik": "1278742"},
    {"id": "greenlight", "name": "그린라이트", "manager": "데이비드 아인혼", "cik": "1079114"},
    {"id": "maverick", "name": "매버릭", "manager": "리 베오니", "cik": "934567"},
    {"id": "farallon", "name": "패럴런", "manager": "톰 스티어스", "cik": "909920"},
    {"id": "glenview", "name": "글렌뷰", "manager": "래리 로빈스", "cik": "1138995"},
    {"id": "jana", "name": "자나 파트너스", "manager": "배리 로젠스타인", "cik": "1159159"},
    {"id": "starboard", "name": "스타보드", "manager": "제프 스미스", "cik": "1517137"},
    {"id": "ark", "name": "아크 인베스트", "manager": "캐시 우드", "cik": "1697745"},
    {"id": "whale_rock", "name": "웨일 록", "manager": "알렉스 샤피로", "cik": "1387322"},
    {"id": "altimeter", "name": "알티미터", "manager": "브래드 게르스터", "cik": "1512855"},
    {"id": "element", "name": "엘리먼트", "manager": "프랭크 펠트", "cik": "1570286"},
    {"id": "holocene", "name": "홀로신", "manager": "브라이언 고틀리브", "cik": "1803146"},
    {"id": "sculptor", "name": "스컬프터", "manager": "", "cik": "1055951"},
    {"id": "aqr", "name": "AQR", "manager": "클리프 애스니스", "cik": "1167557"},
    {"id": "paulson", "name": "폴슨", "manager": "존 폴슨", "cik": "1035674"},
    {"id": "icahn", "name": "아이칸", "manager": "칼 아이칸", "cik": "921134"},
    {"id": "wellington", "name": "웰링턴", "manager": "", "cik": "1446194"},
    {"id": "capital_group", "name": "캐피털 그룹", "manager": "", "cik": "356460"},
    {"id": "trowe", "name": "티로우 프라이스", "manager": "", "cik": "0777513"},
    {"id": "invesco", "name": "인베스코", "manager": "", "cik": "0914208"},
    {"id": "franklin", "name": "프랭클린 템플턴", "manager": "", "cik": "0038771"},
    {"id": "geode", "name": "지오드", "manager": "", "cik": "1214717"},
    {"id": "goldman", "name": "골드만삭스", "manager": "", "cik": "0886982"},
    {"id": "morgan_stanley", "name": "모건스탠리", "manager": "", "cik": "0895421"},
    {"id": "jpmorgan", "name": "JP모건", "manager": "", "cik": "0019617"},
    {"id": "citi", "name": "씨티그룹", "manager": "", "cik": "0831001"},
    {"id": "wells_fargo", "name": "웰스파고", "manager": "", "cik": "0072971"},
    {"id": "northern_trust", "name": "노던 트러스트", "manager": "", "cik": "0073120"},
    {"id": "bny", "name": "BNY 멜론", "manager": "", "cik": "1390777"},
    {"id": "nuveen", "name": "뉴비엔", "manager": "", "cik": "1119774"},
    {"id": "prudential", "name": "프루덴셜", "manager": "", "cik": "1126321"},
    {"id": "alliancebernstein", "name": "얼라이언스번스틴", "manager": "", "cik": "0823128"},
    {"id": "dodge_cox", "name": "다지 앤 콕스", "manager": "", "cik": "0302838"},
    {"id": "american_century", "name": "아메리칸 센추리", "manager": "", "cik": "0718939"},
    {"id": "capital_world", "name": "캐피털 월드", "manager": "", "cik": "0726732"},
    {"id": "harris", "name": "해리스 어소시에이츠", "manager": "", "cik": "0822013"},
    {"id": "lazard", "name": "라자드", "manager": "", "cik": "1085717"},
    {"id": "gmo", "name": "GMO", "manager": "제러미 그램톤", "cik": "1030192"},
    {"id": "egerton", "name": "에거튼", "manager": "존 아르미타지", "cik": "1581180"},
    {"id": "hound", "name": "하운드 파트너스", "manager": "조너선 바라비", "cik": "1471085"},
    {"id": "redmile", "name": "레드마일", "manager": "짐 다일", "cik": "1426325"},
    {"id": "samlyn", "name": "샘린", "manager": "보 라이언", "cik": "1428572"},
    {"id": "eminence", "name": "에미넌스", "manager": "리키 시들러", "cik": "1107312"},
    {"id": "laurion", "name": "라우리온", "manager": "벤 스나더", "cik": "1418814"},
    {"id": "woodline", "name": "우드라인", "manager": "마이클 플리트", "cik": "1843543"},
    {"id": "gates", "name": "게이츠 재단", "manager": "빌 게이츠", "cik": "1166559"},
    {"id": "canyon", "name": "캐니언", "manager": "조시 프리드먼", "cik": "1166003"},
    {"id": "anchorage", "name": "앵커리지", "manager": "케빈 알트", "cik": "1423853"},
    {"id": "king_street", "name": "킹 스트리트", "manager": "브라이언 킹", "cik": "1406313"},
    {"id": "omega", "name": "오메가", "manager": "리언 쿠퍼만", "cik": "940944"},
    {"id": "balyasny", "name": "발리아스니", "manager": "트레이더 밸리", "cik": "1273801"},
    {"id": "exoduspoint", "name": "엑소더스포인트", "manager": "마이클 젤슨", "cik": "1759115"},
    {"id": "surgo", "name": "서고캡", "manager": "", "cik": "1849444"},
    {"id": "dragoneer", "name": "드래고니어", "manager": "", "cik": "1609074"},
    {"id": "alkeon", "name": "알케온", "manager": "", "cik": "1510281"},
    {"id": "jericho", "name": "예리코", "manager": "", "cik": "1510281"},
    {"id": "matrix", "name": "매트릭스", "manager": "", "cik": "1358706"},
    {"id": "tudor", "name": "튜더", "manager": "폴 튜더 존스", "cik": "923093"},
    {"id": "moore", "name": "무어 캐피털", "manager": "루이스 바케티", "cik": "1018969"},
    {"id": "caxton", "name": "캭스턴", "manager": "브루스 코프너", "cik": "847412"},
    {"id": "senvest", "name": "센베스트", "manager": "리처드 마우스", "cik": "1313822"},
    {"id": "durable", "name": "듀러블 캐피털", "manager": "헨리 엘스워스", "cik": "1818810"},
    {"id": "valinor", "name": "밸리노르", "manager": "그렉 애클스", "cik": "1709323"},
    {"id": "capstone", "name": "캡스톤", "manager": "", "cik": "1279429"},
    {"id": "highfields", "name": "하이필즈", "manager": "리처드 버크코위츠", "cik": "1086364"},
    {"id": "mantle_ridge", "name": "맨틀 릿지", "manager": "폴 에이젠", "cik": "1671657"},
    {"id": "engaged", "name": "인게이지드", "manager": "글렌 윌크", "cik": "1599906"},
    {"id": "sachem", "name": "사쳄 헤드", "manager": "스콧 스타브", "cik": "1600045"},
    {"id": "land_buildings", "name": "랜드앤빌딩스", "manager": "조니 모린", "cik": "1600045"},
    {"id": "ubs", "name": "UBS", "manager": "", "cik": "1610520"},
    {"id": "credit_suisse", "name": "크레딧 스위스", "manager": "", "cik": "1055980"},
    {"id": "deutsche_bank", "name": "도이치뱅크", "manager": "", "cik": "1159508"},
    {"id": "barclays", "name": "바클리스", "manager": "", "cik": "1089113"},
    {"id": "amundi", "name": "아문디", "manager": "", "cik": "1454888"},
    {"id": "legal_general", "name": "리걸앤제너럴", "manager": "", "cik": "1081401"},
    {"id": "norges", "name": "노르웨이 국부펀드", "manager": "", "cik": "1374170"},
    {"id": "ontario_teachers", "name": "온타리오 교사연금", "manager": "", "cik": "1351513"},
    {"id": "cppib", "name": "캐나다 연금투자위", "manager": "", "cik": "1351513"},
    {"id": "temasek", "name": "테마섹", "manager": "", "cik": "1001085"},
    {"id": "gic", "name": "싱가포르 GIC", "manager": "", "cik": "1381669"},
    {"id": "baillie", "name": "베일리 기포드", "manager": "", "cik": "1081401"},
    {"id": "orbis", "name": "오르비스", "manager": "", "cik": "1055951"},
    {"id": "ruane", "name": "루안 커니프", "manager": "", "cik": "1036325"},
    {"id": "davis", "name": "데이비스", "manager": "크리스 데이비스", "cik": "0906345"},
    {"id": "primecap", "name": "프라임캡", "manager": "", "cik": "0861967"},
    {"id": "artisan", "name": "아티산", "manager": "", "cik": "1471085"},
    {"id": "wcm", "name": "WCM", "manager": "", "cik": "0906545"},
    {"id": "aiello", "name": "아리엘", "manager": "", "cik": "1015079"},
    {"id": "southeastern", "name": "사우스이스턴", "manager": "메이슨 호킨스", "cik": "0902219"},
    {"id": "third_avenue", "name": "서드 애비뉴", "manager": "마티 화이트맨", "cik": "0923092"},
    {"id": "fairfax", "name": "페어팩스", "manager": "프렘 와쓰", "cik": "915191"},
    {"id": "oaktree", "name": "오크트리", "manager": "하워드 막스", "cik": "1055951"},
    {"id": "ares", "name": "아레스", "manager": "", "cik": "1381669"},
    {"id": "kkr", "name": "KKR", "manager": "", "cik": "1404912"},
    {"id": "apollo", "name": "아폴로", "manager": "", "cik": "1411494"},
    {"id": "carlyle", "name": "칼라일", "manager": "", "cik": "1527166"},
    {"id": "blackstone", "name": "블랙스톤", "manager": "스티븐 슈워츠먼", "cik": "1393818"},
    {"id": "brookfield", "name": "브룩필드", "manager": "", "cik": "1001085"},
    {"id": "tpg", "name": "TPG", "manager": "", "cik": "1880661"},
    {"id": "warburg", "name": "워버그 핀크", "manager": "", "cik": "1381669"},
    {"id": "general_atlantic", "name": "제너럴 애틀랜틱", "manager": "", "cik": "1381669"},
    {"id": "thoma", "name": "토마 브라보", "manager": "", "cik": "1381669"},
    {"id": "vista", "name": "비스타", "manager": "로버트 스미스", "cik": "1381669"},
    {"id": "silver_lake", "name": "실버레이크", "manager": "", "cik": "1381669"},
    {"id": "adage", "name": "아다지", "manager": "", "cik": "1279429"},
    {"id": "lone_cypress", "name": "론 사이프러스", "manager": "", "cik": "1803146"},
    {"id": "palo_alto", "name": "팔로알토", "manager": "", "cik": "1517137"},
    {"id": "rtw", "name": "RTW", "manager": "", "cik": "1793497"},
    {"id": "perceptive", "name": "퍼셉티브", "manager": "", "cik": "1517137"},
    {"id": "orbimed", "name": "오비메드", "manager": "", "cik": "1055951"},
    {"id": "cormorant", "name": "코머런트", "manager": "", "cik": "1609074"},
    {"id": "ra_capital", "name": "RA 캐피털", "manager": "", "cik": "1517137"},
    {"id": "cas", "name": "CAS", "manager": "", "cik": "1517137"},
    {"id": "venbio", "name": "벤바이오", "manager": "", "cik": "1517137"},
    {"id": "boxer", "name": "복서", "manager": "", "cik": "1517137"},
    {"id": "paradigm", "name": "패러다임", "manager": "", "cik": "1517137"},
    {"id": "soroban", "name": "소로반", "manager": "", "cik": "1803146"},
    {"id": "sands_cap", "name": "샌즈 캐피털", "manager": "프랭크 샌즈", "cik": "1029160"},
    {"id": "fisher", "name": "피셔 투자", "manager": "켄 피셔", "cik": "1378871"},
    {"id": "mfs", "name": "MFS", "manager": "", "cik": "60518"},
    {"id": "dimensional", "name": "디멘셔널", "manager": "데이비드 부스", "cik": "354209"},
    {"id": "janus_henderson", "name": "야누스 헨더슨", "manager": "", "cik": "777975"},
    {"id": "macquarie", "name": "맥쿼리", "manager": "", "cik": "1061219"},
    {"id": "clearbridge", "name": "클리어브릿지", "manager": "", "cik": "773762"},
    {"id": "harbor", "name": "하버 캐피털", "manager": "", "cik": "1353316"},
    {"id": "alyeska", "name": "알리에스카", "manager": "스탁 메티슨", "cik": "1555622"},
    {"id": "schonfeld", "name": "숀펠드", "manager": "라이언 스콜크로프트", "cik": "1755786"},
    {"id": "first_eagle", "name": "퍼스트 이글", "manager": "지오프 스타인", "cik": "803016"},
    {"id": "susquehanna", "name": "서스케해나", "manager": "제프 야스", "cik": "1445496"},
    {"id": "concert", "name": "콘서트", "manager": "다이앤 야흐", "cik": "1279936"},
    {"id": "woodson", "name": "우드슨", "manager": "콜린 모런", "cik": "1731134"},
    {"id": "impala", "name": "임팔라", "manager": "보 라이언", "cik": "1628679"},
    {"id": "himalaya", "name": "히말라야", "manager": "리 루", "cik": "1540755"},
    {"id": "select_equity", "name": "셀렉트 이퀴티", "manager": "리차드 피노", "cik": "1510281"},
]

MAX_INSTITUTIONS = 150

# 중복 CIK 제거 (첫 항목 유지)
_seen: set[str] = set()
UNIQUE_INSTITUTIONS: list[dict[str, str]] = []
for row in INSTITUTIONS_13F:
    cik = str(row["cik"]).lstrip("0") or "0"
    key = cik.zfill(10)
    if key in _seen:
        continue
    _seen.add(key)
    UNIQUE_INSTITUTIONS.append({**row, "cik": key})
    if len(UNIQUE_INSTITUTIONS) >= MAX_INSTITUTIONS:
        break