#!/usr/bin/env python3
"""styles.css 의 critical 블록을 index.html / analysis.html 인라인 <style> 에 동기화한다.

단일 소스: styles.css 안의
    /* === critical:start === */ ... /* === critical:end === */
쌍(여러 개 가능)을 순서대로 이어 붙인 것이 critical CSS 다. 주석·빈 줄은 인라인 복사본에서
뺀다(원본 styles.css 는 그대로). HTML 쪽은

    <!-- critical:start -->
    ...(여기가 통째로 바뀐다)...
    <!-- critical:end -->

사이를 다시 쓴다. 마커가 없는 HTML 은 건너뛰고 경고만 낸다. 줄끝(CRLF/LF)은 파일 것을 따른다.

사용:
    py scripts/sync_critical_css.py            # 두 HTML 을 갱신
    py scripts/sync_critical_css.py --check    # 어긋난 파일만 보고, exit 1 (CI 용)

빌드 ID(?v=) 스탬프는 여기서 하지 않는다 — 배포 전 stamp_build_id.py 가 맡는다.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):  # Windows cp949 콘솔에서 한글 깨짐 방지
    try:
        _stream.reconfigure(encoding="utf-8")
    except Exception:
        pass

ROOT = Path(__file__).resolve().parent.parent
STYLES = ROOT / "styles.css"
TARGETS = [ROOT / "index.html", ROOT / "analysis.html"]

CSS_BLOCK = re.compile(r"/\* === critical:start === \*/\r?\n(.*?)/\* === critical:end === \*/", re.S)
HTML_BLOCK = re.compile(r"<!-- critical:start -->.*?<!-- critical:end -->", re.S)
MAX_LINES = 250
LF = chr(10)
CRLF = chr(13) + chr(10)


def strip_comments(css: str) -> str:
    """블록 주석과 빈 줄을 뺀다(인라인 복사본 용). 문자열 안의 '/*' 는 이 파일에 없다."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    lines = [ln.rstrip() for ln in css.replace(CRLF, LF).split(LF)]
    return LF.join(ln for ln in lines if ln.strip())


def extract_critical(styles_text: str) -> str:
    blocks = CSS_BLOCK.findall(styles_text)
    if not blocks:
        sys.exit("styles.css 에 /* === critical:start === */ … /* === critical:end === */ 마커가 없다")
    body = strip_comments(LF.join(blocks))
    n = body.count(LF) + 1
    if n > MAX_LINES:
        print(f"경고: critical CSS 가 {n}줄 — 예산 {MAX_LINES}줄 초과", file=sys.stderr)
    return body


def render_inline(css: str, eol: str) -> str:
    return eol.join([
        "<!-- critical:start -->",
        '<style id="critical-css">',
        "/* generated by scripts/sync_critical_css.py from styles.css — 직접 고치지 말 것 */",
        *css.split(LF),
        "</style>",
        "    <!-- critical:end -->",
    ])


def sync(target: Path, css: str, check: bool) -> bool:
    """True = 이미 최신(또는 갱신 완료). False = 어긋남(--check) 또는 마커 없음."""
    html = target.read_text(encoding="utf-8", newline="")   # 줄끝 보존
    eol = CRLF if CRLF in html else LF
    m = HTML_BLOCK.search(html)
    if not m:
        print(f"[skip] {target.name}: <!-- critical:start --> / <!-- critical:end --> 마커 없음")
        return True
    new_html = html[: m.start()] + render_inline(css, eol) + html[m.end():]
    if new_html == html:
        print(f"[ok]   {target.name}: 최신")
        return True
    if check:
        print(f"[diff] {target.name}: styles.css 의 critical 블록과 다름")
        return False
    target.write_text(new_html, encoding="utf-8", newline="")
    print(f"[sync] {target.name}: 갱신 ({css.count(LF) + 1}줄)")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="갱신하지 않고 어긋남만 보고(exit 1)")
    args = ap.parse_args()

    css = extract_critical(STYLES.read_text(encoding="utf-8", newline=""))
    ok = True
    for t in TARGETS:
        if not t.exists():
            print(f"[skip] {t.name}: 없음")
            continue
        ok = sync(t, css, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
